### ISSUE TITLE
Diferença entre `NFePHP\NFSeNac\RpsInterface` e `NFePHP\NFSeNac\Rps`

### ISSUE THREAD

**Issue by zoiosilva** [nfephp-org/sped-nfse-nacional#37]
** Nota: para questões de suporte, use Google Groups https://groups.google.com/forum/#!forum/nfephp **. Os problemas deste repositório são reservados para solicitações de recursos e relatórios de erros.

* **Estou enviando um ...**
  - [x] bug

* ** Por favor, conte-nos sobre o seu ambiente: **
Windows 10, WSL, Ubuntu 18.04 LTS, php 7.2.

## Comportamento esperado
A classe `NFePHP\NFSeNac\Rps` implementar corretamente a interface `NFePHP\NFSeNac\RpsInterface`.

## Comportamento Atual
Na interface está declarado: `public function render();`
Na classe que a implementa está: `public function render(stdClass $rps = null)`

## Solução possível
Acredito que a declaração na interface esteja incorreta, e deva ser corrigida para ficar de acordo com a assinatura do método na classe.

Também a documentação do método poderia ser transferido para a interface, e deixado só o `{@inheritdoc}` no método.

## Passos para reproduzir
Só olhar o código.

## Contexto (Ambiente)
Eu estou em um ambiente de desenvolvimento local no Drupal 8. Quando fui consumir a interface, me deparei com esta diferença.

**Comment by robmachado** [comment]
Não é bem isso !!

Você pode passar os dados de um RPS no formato stdClass tanto na instanciação da classe como ao executar o metodo render().

É so a nomenclatura que está causando a confusão !!

**Comment by zoiosilva** [comment]
Sim, @robmachado, entendo. Porém a interface que a classe implementa não está permitindo que se passe o stdClass como parâmetro para o método render. E foi isso que sugeri: corrigir a interface para que ela fique igual à classe. Vou abrir um PR com a correção para análise.
